name: easybook
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.5
  font_awesome_flutter: ^10.8.0
  fluentui_icons: ^1.0.0
  dartz: ^0.10.1
  dio: ^5.7.0
  get_it: ^8.0.2
  flutter_bloc: ^8.1.6
  persistent_bottom_nav_bar: ^6.2.1
  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
  - assets/images/



  fonts:
    - family: HankenGrotesk
      fonts:
        - asset: assets/fonts/Hanken_Grotesk/static/HankenGrotesk-Regular.ttf
        - asset: assets/fonts/Hanken_Grotesk/static/HankenGrotesk-Bold.ttf
          weight: 700
        - asset: assets/fonts/Hanken_Grotesk/static/HankenGrotesk-Italic.ttf
          style: italic
